name: PRODUCT_ID
description: The product ID. This is an internal identifier for the product, NOT the SKU.
base_type: type/Integer
database_type: INTEGER
semantic_type: type/FK
fk_target_field_id:
  - Sample Database
  - PUBLIC
  - PRODUCTS
  - ID
table_id:
  - Sample Database
  - PUBLIC
  - ORDERS
active: true
serdes/meta:
  - id: Sample Database
    model: Database
  - id: PUBLIC
    model: Schema
  - id: ORDERS
    model: Table
  - id: PRODUCT_ID
    model: Field
