name: PRODUCT_ID
description: The product the review was for
base_type: type/Integer
database_type: INTEGER
semantic_type: type/FK
fk_target_field_id:
  - Sample Database
  - PUBLIC
  - PRODUCTS
  - ID
table_id:
  - Sample Database
  - PUBLIC
  - REVIEWS
active: true
serdes/meta:
  - id: Sample Database
    model: Database
  - id: PUBLIC
    model: Schema
  - id: REVIEWS
    model: Table
  - id: PRODUCT_ID
    model: Field
