name: PRODUCTS
schema: PUBLIC
description: Includes a catalog of all the products ever sold by the famed Sample Company.
db_id: Sample Database
active: true
serdes/meta:
  - id: Sample Database
    model: Database
  - id: PUBLIC
    model: Schema
  - id: PRODUCTS
    model: Table
